import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 10,
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 10,
  },
  closeBtn: {
    alignSelf: 'flex-end',
    marginBottom: 10,
    padding: 6,
    backgroundColor: 'white',
  },
  closeText: {
    color: '#b30000',
    fontWeight: 'bold',
    fontSize: 16,
  },
  mainTitle: {
    fontSize: 18,
    color: '#b30000',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
  },
  subTitle: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 14,
    marginBottom: 4,
    color: '#333',
  },
  receiptTypeTitle: {
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 13,
    marginBottom: 12,
    color: '#000',
    borderWidth: 1,
    borderColor: '#333',
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignSelf: 'center',
  },
  tinyText: {
    fontSize: 10,
    textAlign: 'center',
    marginBottom: 12,
    color: '#666',
  },
  sectionContainer: {
    marginTop: 10,
    padding: 12,
    backgroundColor: '#f7f7f7',
    borderRadius: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
    color: '#333',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingVertical: 4,
  },
  label: {
    fontWeight: '600',
    flex: 1,
    color: '#555',
  },
  value: {
    flex: 1,
    textAlign: 'right',
    color: '#000',
  },
  declaration: {
    marginTop: 12,
    fontSize: 13,
    lineHeight: 20,
    color: '#333',
  },
  term: {
    fontSize: 12,
    marginVertical: 2,
    color: '#444',
  },
  note: {
    marginTop: 12,
    fontStyle: 'italic',
    fontSize: 11,
    color: '#666',
    textAlign: 'center',
  },
  printBtn: {
    marginTop: 18,
    backgroundColor: '#1E40AF',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
  },
  printText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  divider: {
    height: 1,
    backgroundColor: '#ddd',
    marginVertical: 10,
  },
  totalText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#000',
  },
  dropdown: {
    height: 50,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: '#fff',
  },
  row: {
    marginBottom: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    padding: 10,
    backgroundColor: '#fff',
  },
  submitBtn: {
    backgroundColor: '#b30000',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    marginTop: 15,
  },
  submitText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  documentItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  documentName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  documentDate: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  documentStatus: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 5,
  },
  viewBtn: {
    backgroundColor: '#0c3c78',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 5,
    marginTop: 4,
  },
  viewBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  previewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  previewCloseBtn: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 10,
    padding: 6,
  },
  previewImage: {
    width: '95%',
    height: '75%',
    borderRadius: 10,
  },
  downloadBtn: {
    marginTop: 15,
    backgroundColor: '#0c3c78',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 6,
  },
  downloadText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  // Receipt Modal Styles
  receiptContainer: {
    flex: 1,
    backgroundColor: 'white',
    margin: 20,
    padding: 16,
    borderRadius: 8,
    elevation: 5,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  receiptInfo: {
    marginBottom: 16,
  },
  bold: {
    fontWeight: 'bold',
  },
  tableContainer: {
    borderWidth: 1,
    borderColor: '#ddd',
    marginBottom: 16,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#ddd',
    paddingVertical: 8,
  },
  tableHeaderRow: {
    backgroundColor: '#f1f1f1',
  },
  tableHeaderCell: {
    fontWeight: 'bold',
  },
  tableCell: {
    flex: 1,
    paddingHorizontal: 8,
    fontSize: 12,
    textAlign: 'center',
  },
  qrAndContact: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
  },
  qrImage: {
    width: 100,
    height: 100,
    marginRight: 16,
  },
  contactInfo: {
    flex: 1,
  },
  footerNote: {
    textAlign: 'center',
    fontSize: 12,
    color: '#555',
    marginTop: 10,
  },
  scanBtn: {
    backgroundColor: '#fff',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#1E40AF',
  },
  scanText: {
    color: '#1E40AF',
    fontWeight: 'bold',
    fontSize: 16,
  },
});

export { styles as sharedStyles };
